name: Pangea
description: Blogging about stuffs
meta_description: "Pangea, Blogging about stuffs"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 5
baseurl: /
domain_name: 'http://pangea.party'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://pangea.party'
author:         'Pangea'
authorTwitter:  'PangeaCake'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
